"""The Grinder — ingestion & conversion pipeline.

parse -> gatekeeper duplicate check -> standardize -> write to /repository

Every ground tool lands as a folder:

    repository/<slug>/
        <slug>.py        executable CalcSheet builder (the tool itself)
        <slug>.md        standardized Markdown doc with live values
        manifest.json    metadata consumed by the knowledge graph
        source/<file>    original legacy file, kept for provenance
"""

from __future__ import annotations

import datetime as _dt
import json
import re
import shutil
from dataclasses import dataclass, field
from pathlib import Path

from src.ingestion.base import get_parser
from src.models.calculation import ParsedTool
from src.output_engine import render_markdown


class DuplicateToolError(Exception):
    pass


@dataclass
class GrindResult:
    slug: str
    tool_dir: Path
    files: dict[str, str]
    warnings: list[str] = field(default_factory=list)
    gatekeeper_report: list = field(default_factory=list)
    reuse_findings: list = field(default_factory=list)


def slugify(title: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", title.lower()).strip("_")
    return slug or "unnamed_tool"


def grind(
    source_path: str | Path,
    repo_dir: str | Path = "repository",
    force: bool = False,
    skip_gatekeeper: bool = False,
) -> GrindResult:
    """Convert one legacy file into a standardized repository tool.

    Raises DuplicateToolError when the gatekeeper flags a near-duplicate,
    unless ``force=True`` (the report is still attached to the result so
    reviewers can see what it collided with).
    """
    source_path = Path(source_path)
    repo_dir = Path(repo_dir)
    parsed = get_parser(source_path).parse(source_path)

    report = []
    if not skip_gatekeeper:
        # Imported lazily: the knowledge graph indexes repository content
        # that the grinder itself produces.
        from src.knowledge_graph.gatekeeper import check_submission

        report = check_submission(parsed, repo_dir)
        duplicates = [m for m in report if m.verdict == "duplicate"]
        if duplicates and not force:
            names = ", ".join(m.slug for m in duplicates)
            raise DuplicateToolError(
                f"Gatekeeper: '{parsed.title}' looks like a duplicate of "
                f"existing tool(s): {names}. Re-run with force=True/--force "
                "to override, or extend the existing tool instead."
            )

    # Atomic reuse analysis: which formulas already exist as library
    # atoms or in other tools (single-source-of-truth enforcement).
    from src.knowledge_graph.reuse import analyze_reuse

    reuse_findings = analyze_reuse(parsed, repo_dir)

    slug = slugify(parsed.title)
    tool_dir = repo_dir / slug
    tool_dir.mkdir(parents=True, exist_ok=True)
    (tool_dir / "source").mkdir(exist_ok=True)
    shutil.copy(source_path, tool_dir / "source" / source_path.name)

    files = {
        "python": str(_write_python(parsed, tool_dir, slug)),
        "markdown": str(_write_markdown(parsed, tool_dir, slug)),
        "manifest": str(
            _write_manifest(parsed, tool_dir, slug, reuse_findings)
        ),
    }
    return GrindResult(
        slug=slug,
        tool_dir=tool_dir,
        files=files,
        warnings=parsed.warnings,
        gatekeeper_report=report,
        reuse_findings=reuse_findings,
    )


# ---------------------------------------------------------------------- #
# Standardized artifact writers
# ---------------------------------------------------------------------- #
def _write_python(parsed: ParsedTool, tool_dir: Path, slug: str) -> Path:
    lines: list[str] = []
    lines.append('"""' + parsed.title)
    lines.append("")
    lines.append(f"Auto-generated by The Grinder from "
                 f"{Path(parsed.source_path).name} ({parsed.source_format}).")
    if parsed.description:
        lines.append(parsed.description)
    lines.append('"""')
    lines.append("")
    lines.append("from src.models.calculation import CalcSheet")
    lines.append("")
    lines.append("")
    lines.append("def build_sheet() -> CalcSheet:")
    lines.append("    sheet = CalcSheet(")
    lines.append(f"        title={parsed.title!r},")
    if parsed.description:
        lines.append(f"        description={parsed.description!r},")
    if parsed.reference:
        lines.append(f"        reference={parsed.reference!r},")
    lines.append(f"        tool_id={slug!r},")
    lines.append("    )")

    inputs = [v for v in parsed.variables if v.role == "input"]
    derived = [v for v in parsed.variables if v.role == "derived"]
    if inputs:
        lines.append('    sheet.section("Input Parameters")')
        for var in inputs:
            lines.append(
                f"    sheet.define({var.name!r}, {var.value!r}, "
                f"unit={var.unit!r}, description={var.description!r})"
            )
    if derived:
        lines.append('    sheet.section("Calculation")')
        for var in derived:
            lines.append(
                f"    sheet.calc({var.name!r}, {var.expression!r}, "
                f"unit={var.unit!r}, description={var.description!r})"
            )
    if parsed.checks:
        lines.append('    sheet.section("Verification")')
        for chk in parsed.checks:
            lines.append(f"    sheet.check({chk!r})")
    lines.append("    return sheet")
    lines.append("")
    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append("    from src.output_engine import render_all")
    lines.append('    print(render_all(build_sheet(), "reports"))')
    lines.append("")

    path = tool_dir / f"{slug}.py"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def _write_markdown(parsed: ParsedTool, tool_dir: Path, slug: str) -> Path:
    """Standardized doc = template front matter + live-rendered calc."""
    sheet = parsed.to_sheet()
    front = [
        "---",
        f"tool_id: {slug}",
        f"title: {json.dumps(parsed.title)}",
        "category: uncategorized",
        f"source_file: {Path(parsed.source_path).name}",
        f"source_format: {parsed.source_format}",
        f"reference: {json.dumps(parsed.reference)}",
        "status: converted-unreviewed",
        "reviewed_by: null",
        f"converted: {_dt.date.today().isoformat()}",
        "revision: '0.1'",
        "---",
        "",
    ]
    body = render_markdown(sheet)
    if parsed.warnings:
        warn_block = ["", "## Conversion Warnings", ""]
        warn_block += [f"- ⚠️ {w}" for w in parsed.warnings]
        body += "\n".join(warn_block) + "\n"
    path = tool_dir / f"{slug}.md"
    path.write_text("\n".join(front) + body, encoding="utf-8")
    return path


def _write_manifest(
    parsed: ParsedTool,
    tool_dir: Path,
    slug: str,
    reuse_findings: list | None = None,
) -> Path:
    from src.knowledge_graph.fingerprint import try_fingerprint

    sheet = parsed.to_sheet()
    manifest = {
        "tool_id": slug,
        "title": parsed.title,
        "description": parsed.description,
        "reference": parsed.reference,
        "source_file": Path(parsed.source_path).name,
        "source_format": parsed.source_format,
        "converted": _dt.date.today().isoformat(),
        "status": "converted-unreviewed",
        "variables": [
            {
                "name": v.name,
                "role": v.role,
                "unit": v.unit,
                "description": v.description,
                "expression": v.expression,
                "fingerprint": (
                    try_fingerprint(v.expression) if v.expression else None
                ),
            }
            for v in parsed.variables
        ],
        "checks": parsed.checks,
        "results": sheet.results(),
        "warnings": parsed.warnings,
        "formula_analysis": [
            {
                "name": f.name,
                "status": f.status,
                "match": f.match_id,
            }
            for f in (reuse_findings or [])
        ],
    }
    path = tool_dir / "manifest.json"
    path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return path
