"""Jupyter notebook parser for The Grinder.

Extracts calculation logic from .ipynb files:

- Markdown cells: first ``#`` heading becomes the tool title, other
  headings become sections, plain text becomes descriptions.
- Code cells: simple ``name = expression`` assignments are classified as
  inputs (numeric literal) or derived steps (formula referencing earlier
  names). An inline comment of the form ``# unit | description`` attaches
  metadata, e.g. ``phi = 16  # mm | bar diameter``.
- ``assert``-style or ``name <= name`` comparison lines in a cell tagged
  by a ``# CHECKS`` comment become verification checks.

Anything the parser cannot classify is preserved as a warning so a human
(or an LLM pass, later) can finish the conversion instead of losing logic
silently.
"""

from __future__ import annotations

import ast
import re
from pathlib import Path

import nbformat

from src.ingestion.base import BaseParser
from src.models.calculation import ParsedTool, ParsedVariable

_ASSIGN = re.compile(
    r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*([^#]+?)\s*(?:#\s*(.*))?$"
)
_CHECK = re.compile(
    r"^\s*(?:assert\s+)?"
    r"([A-Za-z_][A-Za-z0-9_]*\s*(?:<=|>=|==|<|>)\s*[A-Za-z0-9_.]+)\s*(?:#.*)?$"
)


def _split_comment(comment: str | None) -> tuple[str, str]:
    """'mm | bar diameter' -> ('mm', 'bar diameter')."""
    if not comment:
        return "", ""
    if "|" in comment:
        unit, desc = comment.split("|", 1)
        return unit.strip(), desc.strip()
    return "", comment.strip()


def _is_literal(expression: str) -> bool:
    try:
        node = ast.parse(expression, mode="eval").body
    except SyntaxError:
        return False
    return isinstance(node, (ast.Constant, ast.UnaryOp)) or (
        isinstance(node, ast.BinOp)
        and all(
            isinstance(n, (ast.Constant, ast.BinOp, ast.UnaryOp))
            for n in ast.walk(node)
            if isinstance(n, ast.expr)
        )
    )


class NotebookParser(BaseParser):
    extensions = (".ipynb",)

    def parse(self, path: Path) -> ParsedTool:
        path = Path(path)
        nb = nbformat.read(str(path), as_version=4)
        tool = ParsedTool(
            title=path.stem.replace("_", " ").title(),
            source_path=str(path),
            source_format="ipynb",
        )
        known: set[str] = set()
        for cell in nb.cells:
            if cell.cell_type == "markdown":
                self._parse_markdown(tool, cell.source)
            elif cell.cell_type == "code":
                self._parse_code(tool, cell.source, known)
        return tool

    def _parse_markdown(self, tool: ParsedTool, source: str) -> None:
        for line in source.splitlines():
            heading = re.match(r"^(#+)\s+(.*)", line.strip())
            if heading and heading.group(1) == "#":
                tool.title = heading.group(2).strip()
            elif not heading and line.strip() and not tool.description:
                tool.description = line.strip()

    def _parse_code(
        self, tool: ParsedTool, source: str, known: set[str]
    ) -> None:
        for line in source.splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith(("#", "import", "from")):
                continue
            if stripped.startswith("print"):
                continue  # display code is regenerated by the output engine
            check = _CHECK.match(stripped)
            if check and not _ASSIGN.match(stripped):
                tool.checks.append(check.group(1).replace(" ", " "))
                continue
            assign = _ASSIGN.match(line)
            if not assign:
                tool.warnings.append(
                    f"Unrecognized line kept for manual review: {stripped!r}"
                )
                continue
            name, expression, comment = assign.groups()
            unit, description = _split_comment(comment)
            expression = expression.strip()
            if _is_literal(expression):
                tool.variables.append(
                    ParsedVariable(
                        name=name,
                        value=float(eval(expression, {"__builtins__": {}})),
                        unit=unit,
                        description=description,
                        role="input",
                    )
                )
            else:
                tool.variables.append(
                    ParsedVariable(
                        name=name,
                        unit=unit,
                        description=description,
                        role="derived",
                        expression=expression,
                    )
                )
            known.add(name)
