"""Markdown renderer: CalcSheet -> Git-friendly Markdown with LaTeX math.

This is the format stored next to every tool in ``/repository`` — reviewable
in any GitHub/GitLab diff, with the math rendered by the platform's built-in
KaTeX/MathJax support.
"""

from __future__ import annotations

from pathlib import Path

from src.models.calculation import CalcSheet, fmt_number, unit_latex

PASS_BADGE = "✅ **OK**"
FAIL_BADGE = "❌ **NOT OK**"


def render_markdown(sheet: CalcSheet, mode: str = "detailed") -> str:
    lines: list[str] = []
    lines.append(f"# {sheet.title}")
    lines.append("")
    meta = [
        ("Project", sheet.project),
        ("Reference", sheet.reference),
        ("Author", sheet.author),
        ("Revision", sheet.revision),
        ("Date", sheet.created),
    ]
    meta = [(k, v) for k, v in meta if v]
    if meta:
        lines.append("| " + " | ".join(k for k, _ in meta) + " |")
        lines.append("|" + "---|" * len(meta))
        lines.append("| " + " | ".join(v for _, v in meta) + " |")
        lines.append("")
    if sheet.description:
        lines.append(sheet.description)
        lines.append("")

    section_no = 0
    input_buffer: list = []

    def flush_inputs() -> None:
        if not input_buffer:
            return
        lines.append("| Symbol | Value | Unit | Description |")
        lines.append("|---|---|---|---|")
        for item in input_buffer:
            symbol = f"${item.latex_lhs}$"
            lines.append(
                f"| {symbol} | {fmt_number(item.value)} | {item.unit} "
                f"| {item.description} |"
            )
        lines.append("")
        input_buffer.clear()

    for item in sheet.items:
        if item.kind == "section":
            flush_inputs()
            section_no += 1
            lines.append(f"## {section_no}. {item.name}")
            lines.append("")
        elif item.kind == "text":
            flush_inputs()
            lines.append(item.text)
            lines.append("")
        elif item.kind == "input":
            input_buffer.append(item)
        elif item.kind == "calc":
            flush_inputs()
            result = fmt_number(item.value)
            rendered_unit = unit_latex(item.unit)
            unit = f"\\ {rendered_unit}" if rendered_unit else ""
            if mode == "compact":
                desc = f" — {item.description}" if item.description else ""
                lines.append(
                    f"$ {item.latex_lhs} = \\mathbf{{{result}}}{unit} ${desc}"
                )
                lines.append("")
            else:
                if item.description:
                    lines.append(f"**{item.description}**")
                    lines.append("")
                lines.append("$$")
                lines.append("\\begin{aligned}")
                lines.append(f"{item.latex_lhs} &= {item.latex_symbolic} \\\\")
                lines.append(f"&= {item.latex_substituted} \\\\")
                lines.append(f"&= \\mathbf{{{result}}}{unit}")
                lines.append("\\end{aligned}")
                lines.append("$$")
                lines.append("")
        elif item.kind == "check":
            flush_inputs()
            badge = PASS_BADGE if item.passed else FAIL_BADGE
            desc = f" — {item.description}" if item.description else ""
            lines.append(f"> {badge}{desc}")
            lines.append(">")
            lines.append(f"> $$ {item.latex_symbolic} $$")
            lines.append("")
    flush_inputs()

    lines.append("---")
    lines.append(
        "*Generated by the Structural AI Toolchain output engine — values "
        "above are computed live from the paired Python tool, not typed in.*"
    )
    lines.append("")
    return "\n".join(lines)


def math_to_markdown(
    sheet: CalcSheet, out_path: str | Path
) -> Path:
    """Convenience wrapper: render a sheet's math to a Markdown file."""
    path = Path(out_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_markdown(sheet), encoding="utf-8")
    return path
