"""Rectangular Beam Bending Check

Auto-generated by The Grinder from beam_bending_check.ipynb (ipynb).
Elastic bending stress verification for a simply supported rectangular timber beam under uniform load.
"""

from src.models.calculation import CalcSheet


def build_sheet() -> CalcSheet:
    sheet = CalcSheet(
        title='Rectangular Beam Bending Check',
        description='Elastic bending stress verification for a simply supported rectangular timber beam under uniform load.',
        tool_id='rectangular_beam_bending_check',
    )
    sheet.section("Input Parameters")
    sheet.define('b', 200.0, unit='mm', description='Section width')
    sheet.define('h', 400.0, unit='mm', description='Section depth')
    sheet.define('L', 5000.0, unit='mm', description='Span')
    sheet.define('q', 4.5, unit='kN/m', description='Distributed load (design)')
    sheet.define('f_m', 24.0, unit='MPa', description='Design bending strength')
    sheet.section("Calculation")
    sheet.calc('M_max', 'q*(L/1000)**2/8', unit='kNm', description='Maximum bending moment')
    sheet.calc('W', 'b*h**2/6', unit='mm^3', description='Elastic section modulus')
    sheet.calc('sigma_m', 'M_max*1000000/W', unit='MPa', description='Maximum bending stress')
    sheet.section("Verification")
    sheet.check('sigma_m <= f_m')
    return sheet


if __name__ == "__main__":
    from src.output_engine import render_all
    print(render_all(build_sheet(), "reports"))
