"""Simply Supported Steel Beam — quick check

Auto-generated by The Grinder from messy_beam.xlsx (xlsx).
"""

from src.models.calculation import CalcSheet


def build_sheet() -> CalcSheet:
    sheet = CalcSheet(
        title='Simply Supported Steel Beam — quick check',
        tool_id='simply_supported_steel_beam_quick_check',
    )
    sheet.section("Input Parameters")
    sheet.define('beam_h1', 1.0, unit='', description='beam_h1')
    sheet.define('Span_L', 6.0, unit='m', description='Span L (m)')
    sheet.define('Line_load_w', 12.0, unit='kN/m', description='Line load w (kN/m)')
    sheet.define('Section_modulus_Wel', 324.0, unit='cm3', description='Section modulus Wel (cm3)')
    sheet.define('Yield_fy', 355.0, unit='MPa', description='Yield fy (MPa)')
    sheet.define('factors_b2', 1.0, unit='', description='factors_b2')
    sheet.section("Calculation")
    sheet.calc('Moment_M', 'Line_load_w*Span_L**2/8', unit='kNm', description='Moment M (kNm)')
    sheet.calc('Bending_stress_sigma', 'Moment_M*1000/Section_modulus_Wel*factors_b2', unit='MPa', description='Bending stress sigma (MPa)')
    sheet.section("Verification")
    sheet.check('Bending_stress_sigma<=Yield_fy')
    return sheet


if __name__ == "__main__":
    from src.output_engine import render_all
    print(render_all(build_sheet(), "reports"))
