"""Crack Width Verification - RC Slab (EN 1992-1-1 7.3.4)

Auto-generated by The Grinder from crack_width_ec2.xlsx (xlsx).
Characteristic crack width for a reinforced concrete slab under quasi-permanent loading.
"""

from src.models.calculation import CalcSheet


def build_sheet() -> CalcSheet:
    sheet = CalcSheet(
        title='Crack Width Verification - RC Slab (EN 1992-1-1 7.3.4)',
        description='Characteristic crack width for a reinforced concrete slab under quasi-permanent loading.',
        tool_id='crack_width_verification_rc_slab_en_1992_1_1_7_3_4',
    )
    sheet.section("Input Parameters")
    sheet.define('b', 1000.0, unit='mm', description='Section width (per metre strip)')
    sheet.define('h', 300.0, unit='mm', description='Section depth')
    sheet.define('d', 260.0, unit='mm', description='Effective depth')
    sheet.define('c_nom', 30.0, unit='mm', description='Nominal concrete cover')
    sheet.define('phi', 16.0, unit='mm', description='Bar diameter')
    sheet.define('A_s', 1005.0, unit='mm^2', description='Tension reinforcement area (5 H16)')
    sheet.define('M_qp', 45.0, unit='kNm', description='Quasi-permanent bending moment')
    sheet.define('E_s', 200000.0, unit='MPa', description='Steel modulus of elasticity')
    sheet.define('E_cm', 33000.0, unit='MPa', description='Concrete secant modulus')
    sheet.define('f_ct_eff', 2.9, unit='MPa', description='Effective concrete tensile strength')
    sheet.define('k_t', 0.4, unit='-', description='Load duration factor (long term)')
    sheet.define('k_1', 0.8, unit='-', description='Bond factor (high-bond bars)')
    sheet.define('k_2', 0.5, unit='-', description='Strain distribution factor (bending)')
    sheet.define('k_3', 3.4, unit='-', description='Code coefficient')
    sheet.define('k_4', 0.425, unit='-', description='Code coefficient')
    sheet.define('w_max', 0.3, unit='mm', description='Allowable crack width (XC exposure)')
    sheet.section("Calculation")
    sheet.calc('alpha_e', 'E_s/E_cm', unit='-', description='Modular ratio E_s/E_cm')
    sheet.calc('x', '(alpha_e*A_s/b)*(sqrt(1+2*b*d/(alpha_e*A_s))-1)', unit='mm', description='Neutral axis depth (cracked section)')
    sheet.calc('z', 'd-x/3', unit='mm', description='Internal lever arm')
    sheet.calc('sigma_s', 'M_qp*1000000/(z*A_s)', unit='MPa', description='Steel stress under quasi-permanent loads')
    sheet.calc('h_c_eff', 'min(2.5*(h-d),(h-x)/3,h/2)', unit='mm', description='Effective tension zone height')
    sheet.calc('rho_p_eff', 'A_s/(b*h_c_eff)', unit='-', description='Effective reinforcement ratio')
    sheet.calc('s_r_max', 'k_3*c_nom+k_1*k_2*k_4*phi/rho_p_eff', unit='mm', description='Maximum crack spacing')
    sheet.calc('eps_diff', 'max((sigma_s-k_t*f_ct_eff/rho_p_eff*(1+alpha_e*rho_p_eff))/E_s,0.6*sigma_s/E_s)', unit='-', description='Mean strain difference (eps_sm - eps_cm)')
    sheet.calc('w_k', 's_r_max*eps_diff', unit='mm', description='Characteristic crack width')
    sheet.section("Verification")
    sheet.check('w_k <= w_max')
    return sheet


if __name__ == "__main__":
    from src.output_engine import render_all
    print(render_all(build_sheet(), "reports"))
